/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "api.departments.byBranch": [],
    "home": [],
    "offline": [],
    "pre-orders.miniapp": [],
    "memos.pdf": [
        {
            "name": "memo",
            "required": true
        }
    ],
    "dashboard": [],
    "sync.inventory-counts": [],
    "sync.evaluations": [],
    "sync.pending-count": [],
    "permissions.index": [],
    "permissions.store": [],
    "permissions.update": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.destroy": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.matrix": [],
    "roles.matrix.toggle": [],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.edit": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "users.export": [],
    "users.toggle-status": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.index": [],
    "departments.create": [],
    "departments.store": [],
    "departments.edit": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.export": [],
    "branches.index": [],
    "branches.create": [],
    "branches.store": [],
    "branches.show": [
        {
            "name": "branch",
            "required": true
        }
    ],
    "branches.edit": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "branches.update": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "branches.destroy": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "positions.index": [],
    "positions.create": [],
    "positions.store": [],
    "positions.show": [
        {
            "name": "position",
            "required": true
        }
    ],
    "positions.edit": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "positions.update": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "positions.destroy": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "departments.show": [
        {
            "name": "department",
            "required": true
        }
    ],
    "employees.index": [],
    "employees.create": [],
    "employees.store": [],
    "employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.edit": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "holidays.index": [],
    "holidays.create": [],
    "holidays.store": [],
    "holidays.show": [
        {
            "name": "holiday",
            "required": true
        }
    ],
    "holidays.edit": [
        {
            "name": "holiday",
            "required": true
        }
    ],
    "holidays.update": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "holidays.destroy": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "employee-directory.index": [],
    "managers.index": [],
    "managers.create": [],
    "managers.store": [],
    "managers.edit": [
        {
            "name": "manager",
            "required": true,
            "binding": "id"
        }
    ],
    "managers.update": [
        {
            "name": "manager",
            "required": true,
            "binding": "id"
        }
    ],
    "managers.destroy": [
        {
            "name": "manager",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluation-types.index": [],
    "evaluation-types.create": [],
    "evaluation-types.store": [],
    "evaluation-types.edit": [
        {
            "name": "evaluation_type",
            "required": true
        }
    ],
    "evaluation-types.update": [
        {
            "name": "evaluation_type",
            "required": true
        }
    ],
    "evaluation-types.destroy": [
        {
            "name": "evaluation_type",
            "required": true
        }
    ],
    "question-groups.index": [],
    "question-groups.create": [],
    "question-groups.store": [],
    "question-groups.edit": [
        {
            "name": "question_group",
            "required": true,
            "binding": "id"
        }
    ],
    "question-groups.update": [
        {
            "name": "question_group",
            "required": true,
            "binding": "id"
        }
    ],
    "question-groups.destroy": [
        {
            "name": "question_group",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.index": [],
    "questions.create": [],
    "questions.store": [],
    "questions.edit": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.update": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.destroy": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluator-groups.index": [],
    "evaluator-groups.create": [],
    "evaluator-groups.store": [],
    "evaluator-groups.edit": [
        {
            "name": "evaluator_group",
            "required": true
        }
    ],
    "evaluator-groups.update": [
        {
            "name": "evaluator_group",
            "required": true
        }
    ],
    "evaluator-groups.destroy": [
        {
            "name": "evaluator_group",
            "required": true
        }
    ],
    "evaluates-groups.index": [],
    "evaluates-groups.create": [],
    "evaluates-groups.store": [],
    "evaluates-groups.edit": [
        {
            "name": "evaluates_group",
            "required": true
        }
    ],
    "evaluates-groups.update": [
        {
            "name": "evaluates_group",
            "required": true
        }
    ],
    "evaluates-groups.destroy": [
        {
            "name": "evaluates_group",
            "required": true
        }
    ],
    "other-evaluables.index": [],
    "other-evaluables.create": [],
    "other-evaluables.store": [],
    "other-evaluables.edit": [
        {
            "name": "other_evaluable",
            "required": true
        }
    ],
    "other-evaluables.update": [
        {
            "name": "other_evaluable",
            "required": true
        }
    ],
    "other-evaluables.destroy": [
        {
            "name": "other_evaluable",
            "required": true
        }
    ],
    "evaluations.index": [],
    "evaluations.create": [],
    "evaluations.store": [],
    "evaluations.edit": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluations.update": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluations.destroy": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "fiscal-years.index": [],
    "fiscal-years.create": [],
    "fiscal-years.store": [],
    "fiscal-years.edit": [
        {
            "name": "fiscal_year",
            "required": true
        }
    ],
    "fiscal-years.update": [
        {
            "name": "fiscal_year",
            "required": true
        }
    ],
    "fiscal-years.destroy": [
        {
            "name": "fiscal_year",
            "required": true
        }
    ],
    "fiscal-months.index": [],
    "fiscal-months.create": [],
    "fiscal-months.store": [],
    "fiscal-months.edit": [
        {
            "name": "fiscal_month",
            "required": true
        }
    ],
    "fiscal-months.update": [
        {
            "name": "fiscal_month",
            "required": true
        }
    ],
    "fiscal-months.destroy": [
        {
            "name": "fiscal_month",
            "required": true
        }
    ],
    "evaluation-periods.index": [],
    "evaluation-periods.create": [],
    "evaluation-periods.store": [],
    "evaluation-periods.edit": [
        {
            "name": "evaluation_period",
            "required": true
        }
    ],
    "evaluation-periods.update": [
        {
            "name": "evaluation_period",
            "required": true
        }
    ],
    "evaluation-periods.destroy": [
        {
            "name": "evaluation_period",
            "required": true
        }
    ],
    "evaluation-categories.index": [],
    "evaluation-categories.create": [],
    "evaluation-categories.store": [],
    "evaluation-categories.edit": [
        {
            "name": "evaluation_category",
            "required": true
        }
    ],
    "evaluation-categories.update": [
        {
            "name": "evaluation_category",
            "required": true
        }
    ],
    "evaluation-categories.destroy": [
        {
            "name": "evaluation_category",
            "required": true
        }
    ],
    "child-categories.index": [],
    "child-categories.create": [],
    "child-categories.store": [],
    "child-categories.edit": [
        {
            "name": "child_category",
            "required": true
        }
    ],
    "child-categories.update": [
        {
            "name": "child_category",
            "required": true
        }
    ],
    "child-categories.destroy": [
        {
            "name": "child_category",
            "required": true
        }
    ],
    "products.toggle-purchasable": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "inventory-periods.index": [],
    "inventory-periods.create": [],
    "inventory-periods.store": [],
    "inventory-periods.edit": [
        {
            "name": "inventory_period",
            "required": true
        }
    ],
    "inventory-periods.update": [
        {
            "name": "inventory_period",
            "required": true
        }
    ],
    "inventory-periods.destroy": [
        {
            "name": "inventory_period",
            "required": true
        }
    ],
    "forms.available": [],
    "forms.fill": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.fill.store": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.index": [],
    "forms.create": [],
    "forms.store": [],
    "forms.show": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.edit": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.update": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.versions": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.permissions": [
        {
            "name": "form",
            "required": true,
            "binding": "id"
        }
    ],
    "forms.permissions.update": [
        {
            "name": "form",
            "required": true,
            "binding": "id"
        }
    ],
    "forms.import": [],
    "forms.import.version": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.export": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.destroy": [
        {
            "name": "form",
            "required": true
        }
    ],
    "forms.submissions.index": [],
    "forms.submissions.by_form": [
        {
            "name": "form",
            "required": true,
            "binding": "id"
        }
    ],
    "forms.submissions.show": [
        {
            "name": "submission",
            "required": true
        }
    ],
    "submissions.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "submissions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "submissions.update_status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "forms.submissions.export": [
        {
            "name": "form",
            "required": true,
            "binding": "id"
        }
    ],
    "submissions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "expense-budget-periods.index": [],
    "expense-budget-periods.create": [],
    "expense-budget-periods.store": [],
    "expense-budget-periods.edit": [
        {
            "name": "expense_budget_period",
            "required": true
        }
    ],
    "expense-budget-periods.update": [
        {
            "name": "expense_budget_period",
            "required": true
        }
    ],
    "expense-budget-periods.destroy": [
        {
            "name": "expense_budget_period",
            "required": true
        }
    ],
    "weekly-budget-periods.index": [],
    "weekly-budget-periods.store": [],
    "inventory-counts.auto-save": [],
    "inventory-counts.previous": [],
    "inventory-counts.bulk": [],
    "inventory-counts.approve": [
        {
            "name": "inventoryCount",
            "required": true,
            "binding": "id"
        }
    ],
    "inventory-counts.unapprove": [
        {
            "name": "inventoryCount",
            "required": true,
            "binding": "id"
        }
    ],
    "inventory-counts.bulk-approve": [],
    "inventory-counts.bulk-unapprove": [],
    "inventory-counts.index": [],
    "inventory-counts.create": [],
    "inventory-counts.store": [],
    "inventory-counts.edit": [
        {
            "name": "inventory_count",
            "required": true
        }
    ],
    "inventory-counts.update": [
        {
            "name": "inventory_count",
            "required": true
        }
    ],
    "inventory-counts.destroy": [
        {
            "name": "inventory_count",
            "required": true
        }
    ],
    "inventory-completion-tracking.index": [],
    "inventory-completion-tracking.missing-categories": [
        {
            "name": "branch",
            "required": true
        },
        {
            "name": "period",
            "required": true
        }
    ],
    "my-evaluation.index": [],
    "my-evaluation.history": [],
    "my-evaluation.response.view": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-evaluation.response.edit": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-evaluation.response.update": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-evaluation.response.destroy": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-evaluation.show": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "my-evaluation.store": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "my-results.index": [],
    "my-results.show": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-results.accept": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "my-results.reject": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "rejected-evaluations.index": [],
    "rejected-evaluations.approve": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "rejected-evaluations.cancel": [
        {
            "name": "evaluationResponse",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluator-completion.index": [],
    "memos.sign-cc": [
        {
            "name": "memo",
            "required": true
        }
    ],
    "memos.send-telegram": [
        {
            "name": "memo",
            "required": true,
            "binding": "id"
        }
    ],
    "memos.index": [],
    "memos.create": [],
    "memos.store": [],
    "memos.show": [
        {
            "name": "memo",
            "required": true,
            "binding": "id"
        }
    ],
    "memos.edit": [
        {
            "name": "memo",
            "required": true,
            "binding": "id"
        }
    ],
    "memos.update": [
        {
            "name": "memo",
            "required": true,
            "binding": "id"
        }
    ],
    "memos.destroy": [
        {
            "name": "memo",
            "required": true,
            "binding": "id"
        }
    ],
    "memo-templates.index": [],
    "memo-templates.store": [],
    "memo-templates.destroy": [
        {
            "name": "memo_template",
            "required": true
        }
    ],
    "memo-settings.index": [],
    "memo-settings.update": [],
    "user.signature.update": [],
    "reports.evaluation-summary": [],
    "reports.evaluation-summary.details": [],
    "reports.evaluation-summary.export": [],
    "evaluation-records.index": [],
    "evaluation-records.edit": [
        {
            "name": "evaluation_record",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluation-records.update": [
        {
            "name": "evaluation_record",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluation-records.destroy": [
        {
            "name": "evaluation_record",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.finance.export": [],
    "weekly-budget.finance": [],
    "weekly-budget.finance.send-to-ceo": [],
    "weekly-budget.update-finance": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.bulk-update-finance": [],
    "weekly-budget.override-paid": [],
    "weekly-budget.department.export": [],
    "weekly-budget.department": [],
    "weekly-budget.update-department": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.department-delete": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.bulk-update-department": [],
    "weekly-budget.ceo.export": [],
    "weekly-budget.ceo": [],
    "weekly-budget.update-ceo": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.bulk-update-ceo": [],
    "weekly-budget.index.export": [],
    "weekly-budget.index": [],
    "weekly-budget.activity-logs": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.analytics": [],
    "weekly-budget.create": [],
    "weekly-budget.store": [],
    "weekly-budget.update": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget.destroy": [
        {
            "name": "weeklyBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "weekly-budget-notifications.index": [],
    "weekly-budget-notifications.mark-read": [
        {
            "name": "notification",
            "required": false,
            "binding": "id"
        }
    ],
    "weekly-budget-notifications.clear": [],
    "external-links.index": [],
    "external-links.store": [],
    "external-links.update": [
        {
            "name": "external_link",
            "required": true,
            "binding": "id"
        }
    ],
    "external-links.destroy": [
        {
            "name": "external_link",
            "required": true,
            "binding": "id"
        }
    ],
    "external-link-sections.store": [],
    "external-link-sections.update": [
        {
            "name": "external_link_section",
            "required": true,
            "binding": "id"
        }
    ],
    "external-link-sections.destroy": [
        {
            "name": "external_link_section",
            "required": true,
            "binding": "id"
        }
    ],
    "deleted-evaluations.index": [],
    "deleted-evaluations.restore": [
        {
            "name": "deleted_evaluation",
            "required": true,
            "binding": "id"
        }
    ],
    "reports.employee-evaluations.index": [],
    "reports.branch-manager-evaluation-summary": [],
    "reports.branch-manager-evaluation-summary.details": [],
    "reports.branch-manager-evaluation-summary.export": [],
    "reports.champions-evaluation-summary": [],
    "reports.champions-evaluation-summary.export": [],
    "reports.champions-evaluation-summary.details": [],
    "reports.regional-production-maintenance-summary": [],
    "reports.regional-production-maintenance-summary.export": [],
    "reports.regional-production-maintenance-summary.details": [],
    "reports.inventory-count-summary": [],
    "reports.inventory-count-summary.export": [],
    "pre-orders.dashboard": [],
    "pre-orders.feedback.index": [],
    "pre-orders.feedback.export": [],
    "pre-orders.feedback.destroy": [
        {
            "name": "feedback",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-orders.customers.index": [],
    "pre-orders.customers.export": [],
    "pre-orders.broadcasts.index": [],
    "pre-orders.broadcasts.store": [],
    "pre-orders.export": [],
    "pre-orders.update-status": [
        {
            "name": "preOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-orders.send-bulk-sms-reminders": [],
    "pre-orders.bulk-cancel": [],
    "pre-orders.sms-templates.index": [],
    "pre-orders.sms-templates.update": [
        {
            "name": "smsTemplate",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-order-payment-settings.admin-chat-id": [],
    "pre-order-payment-settings.index": [],
    "pre-order-payment-settings.store": [],
    "pre-order-payment-settings.update": [
        {
            "name": "pre_order_payment_setting",
            "required": true
        }
    ],
    "pre-order-costs.categories.index": [],
    "pre-order-costs.categories.store": [],
    "pre-order-costs.categories.update": [
        {
            "name": "preOrderCostCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-order-costs.categories.destroy": [
        {
            "name": "preOrderCostCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-order-costs.index": [],
    "pre-order-costs.store": [],
    "pre-order-costs.update": [
        {
            "name": "preOrderCost",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-order-costs.destroy": [
        {
            "name": "preOrderCost",
            "required": true,
            "binding": "id"
        }
    ],
    "pre-order-costs.bulk-update-products": [],
    "pre-order-costs.active-products": [],
    "pre-orders.index": [],
    "pre-orders.create": [],
    "pre-orders.store": [],
    "pre-orders.show": [
        {
            "name": "pre_order",
            "required": true
        }
    ],
    "pre-orders.edit": [
        {
            "name": "pre_order",
            "required": true
        }
    ],
    "pre-orders.update": [
        {
            "name": "pre_order",
            "required": true
        }
    ],
    "pre-orders.destroy": [
        {
            "name": "pre_order",
            "required": true
        }
    ],
    "my-branch-orders.index": [],
    "my-branch-orders.export": [],
    "my-branch-orders.collect": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "my-branch-orders.uncollect": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "sms-balance.index": [],
    "sms-balance.api": [],
    "sms-balance.activate": [],
    "sms-balance.deactivate": [],
    "tickets.reports": [],
    "tickets.reports.send-telegram": [],
    "tickets.index": [],
    "tickets.store-balance": [],
    "tickets.export": [],
    "tickets.create": [],
    "tickets.store": [],
    "tickets.show": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.quick-update": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.download-products": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.status": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.assign": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.approve-completion": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.reject-completion": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.rate": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.chat": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.approve-rate": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.update-asset": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.update-deadline": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.update-priority": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "tickets.destroy": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket-notifications.index": [],
    "ticket-notifications.mark-read": [
        {
            "name": "notification",
            "required": false,
            "binding": "id"
        }
    ],
    "ticket-notifications.clear": [],
    "ticket-settings.index": [],
    "ticket-settings.main-categories": [],
    "ticket-settings.sub-categories": [],
    "ticket-settings.assets": [],
    "ticket-sub-categories.toggle-status": [
        {
            "name": "ticketSubCategory",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket-main-categories.index": [],
    "ticket-main-categories.create": [],
    "ticket-main-categories.store": [],
    "ticket-main-categories.edit": [
        {
            "name": "ticket_main_category",
            "required": true
        }
    ],
    "ticket-main-categories.update": [
        {
            "name": "ticket_main_category",
            "required": true
        }
    ],
    "ticket-main-categories.destroy": [
        {
            "name": "ticket_main_category",
            "required": true
        }
    ],
    "ticket-sub-categories.index": [],
    "ticket-sub-categories.create": [],
    "ticket-sub-categories.store": [],
    "ticket-sub-categories.edit": [
        {
            "name": "ticket_sub_category",
            "required": true
        }
    ],
    "ticket-sub-categories.update": [
        {
            "name": "ticket_sub_category",
            "required": true
        }
    ],
    "ticket-sub-categories.destroy": [
        {
            "name": "ticket_sub_category",
            "required": true
        }
    ],
    "ticket-assets.index": [],
    "ticket-assets.create": [],
    "ticket-assets.store": [],
    "ticket-assets.edit": [
        {
            "name": "ticket_asset",
            "required": true
        }
    ],
    "ticket-assets.update": [
        {
            "name": "ticket_asset",
            "required": true
        }
    ],
    "ticket-assets.destroy": [
        {
            "name": "ticket_asset",
            "required": true
        }
    ],
    "spare-part-categories.index": [],
    "spare-part-categories.create": [],
    "spare-part-categories.store": [],
    "spare-part-categories.edit": [
        {
            "name": "spare_part_category",
            "required": true
        }
    ],
    "spare-part-categories.update": [
        {
            "name": "spare_part_category",
            "required": true
        }
    ],
    "spare-part-categories.destroy": [
        {
            "name": "spare_part_category",
            "required": true
        }
    ],
    "spare-parts.index": [],
    "spare-parts.create": [],
    "spare-parts.store": [],
    "spare-parts.edit": [
        {
            "name": "spare_part",
            "required": true
        }
    ],
    "spare-parts.update": [
        {
            "name": "spare_part",
            "required": true
        }
    ],
    "spare-parts.destroy": [
        {
            "name": "spare_part",
            "required": true
        }
    ],
    "broadcast-announcements.index": [],
    "broadcast-announcements.send": [],
    "telegram-config.index": [],
    "telegram-config.update-settings": [],
    "telegram-config.set-webhook": [],
    "telegram-config.remove-webhook": [],
    "telegram-config.test-message": [],
    "telegram-config.update-user": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "telegram-config.update-branch": [
        {
            "name": "branch",
            "required": true,
            "binding": "id"
        }
    ],
    "telegram-config.broadcast": [],
    "telegram-config.bots.store": [],
    "telegram-config.bots.update": [
        {
            "name": "bot",
            "required": true,
            "binding": "id"
        }
    ],
    "telegram-config.bots.destroy": [
        {
            "name": "bot",
            "required": true,
            "binding": "id"
        }
    ],
    "telegram-config.bots.set-webhook": [
        {
            "name": "bot",
            "required": true,
            "binding": "id"
        }
    ],
    "telegram-config.bots.remove-webhook": [
        {
            "name": "bot",
            "required": true,
            "binding": "id"
        }
    ],
    "kaldis-communication.index": [],
    "kaldis-communication.update-config": [],
    "kaldis-communication.store-binding": [],
    "kaldis-communication.update-binding": [],
    "kaldis-communication.delete-binding": [],
    "kaldis-communication.store-user": [],
    "kaldis-communication.update-user": [],
    "kaldis-communication.delete-user": [
        {
            "name": "telegramUserId",
            "required": true
        }
    ],
    "kaldis-communication.sync-members": [],
    "kaldis-communication.fetch-member": [],
    "kaldis-communication.update-status": [
        {
            "name": "referenceNo",
            "required": true
        }
    ],
    "kaldis-communication.sync-topics": [],
    "kaldis-communication.bulk-delete-bindings": [],
    "kaldis-communication.moderation.settings": [],
    "kaldis-communication.moderation.member": [],
    "kaldis-communication.moderation.broadcast": [],
    "kaldis-communication.register-commands": [],
    "kaldis-communication.set-webhook": [],
    "kaldis-communication.generate-invite-link": [],
    "kaldis-communication.purge-unlisted": [],
    "kaldis-communication.store-standard-topic": [],
    "kaldis-communication.update-standard-topic": [],
    "kaldis-communication.delete-standard-topic": [],
    "telecom.dashboard": [],
    "telecom.phone-numbers.export": [],
    "telecom.phone-numbers.transfer": [
        {
            "name": "phoneNumber",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.phone-numbers.index": [],
    "telecom.phone-numbers.create": [],
    "telecom.phone-numbers.store": [],
    "phone-numbers.show": [
        {
            "name": "phone_number",
            "required": true
        }
    ],
    "telecom.phone-numbers.edit": [
        {
            "name": "phone_number",
            "required": true
        }
    ],
    "telecom.phone-numbers.update": [
        {
            "name": "phone_number",
            "required": true
        }
    ],
    "telecom.phone-numbers.destroy": [
        {
            "name": "phone_number",
            "required": true
        }
    ],
    "telecom.broadbands.export": [],
    "telecom.broadbands.transfer": [
        {
            "name": "broadband",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.broadbands.index": [],
    "telecom.broadbands.create": [],
    "telecom.broadbands.store": [],
    "broadbands.show": [
        {
            "name": "broadband",
            "required": true
        }
    ],
    "telecom.broadbands.edit": [
        {
            "name": "broadband",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.broadbands.update": [
        {
            "name": "broadband",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.broadbands.destroy": [
        {
            "name": "broadband",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.providers.index": [],
    "telecom.providers.store": [],
    "telecom.providers.update": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "telecom.providers.destroy": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "training.dashboard": [],
    "training.courses.index": [],
    "training.courses.create": [],
    "training.courses.store": [],
    "training.courses.show": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.courses.edit": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.courses.update": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.courses.destroy": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.courses.enroll": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.courses.lessons.store": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "training.lessons.show": [
        {
            "name": "lesson",
            "required": true,
            "binding": "id"
        }
    ],
    "training.lessons.complete": [
        {
            "name": "lesson",
            "required": true,
            "binding": "id"
        }
    ],
    "training.my-learning.index": [],
    "training.question-banks.index": [],
    "training.question-banks.store": [],
    "training.question-banks.update": [
        {
            "name": "questionBank",
            "required": true,
            "binding": "id"
        }
    ],
    "training.question-banks.destroy": [
        {
            "name": "questionBank",
            "required": true,
            "binding": "id"
        }
    ],
    "training.quizzes.index": [],
    "training.quizzes.store": [],
    "training.quizzes.take": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "training.quizzes.submit": [
        {
            "name": "quiz",
            "required": true,
            "binding": "id"
        }
    ],
    "training.ai-quiz.index": [],
    "training.ai-quiz.generate": [],
    "training.certificates.index": [],
    "training.certificates.revoke": [
        {
            "name": "certificate",
            "required": true,
            "binding": "id"
        }
    ],
    "training.certificates.verify": [],
    "training.leaderboard.index": [],
    "training.badges.index": [],
    "training.badges.store": [],
    "training.sop.index": [],
    "training.sop.store": [],
    "training.sop.show": [
        {
            "name": "sop",
            "required": true,
            "binding": "id"
        }
    ],
    "training.sop.acknowledge": [
        {
            "name": "sop",
            "required": true,
            "binding": "id"
        }
    ],
    "training.sop.destroy": [
        {
            "name": "sop",
            "required": true,
            "binding": "id"
        }
    ],
    "training.agendas.index": [],
    "training.agendas.create": [],
    "training.agendas.store": [],
    "training.agendas.show": [
        {
            "name": "agenda",
            "required": true,
            "binding": "id"
        }
    ],
    "training.schedules.index": [],
    "training.schedules.create": [],
    "training.schedules.store": [],
    "training.schedules.publish": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "training.schedules.items.approve": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "training.attendance.index": [],
    "training.attendance.store": [],
    "training.attendance.toggle": [],
    "training.attendance.update-status": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "training.feedback.index": [],
    "training.feedback.create": [],
    "training.feedback.store": [],
    "training.settings.index": [],
    "training.settings.update": [],
    "training.agendas.check-in": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "training.forums.index": [],
    "training.forums.store": [],
    "training.forums.thread": [
        {
            "name": "thread",
            "required": true,
            "binding": "id"
        }
    ],
    "training.forums.threads.store": [
        {
            "name": "forum",
            "required": true,
            "binding": "id"
        }
    ],
    "training.forums.reply": [
        {
            "name": "thread",
            "required": true,
            "binding": "id"
        }
    ],
    "training.forums.mark-solution": [
        {
            "name": "thread",
            "required": true,
            "binding": "id"
        },
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "training.reports.index": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "pre-order-products.index": [],
    "pre-order-products.create": [],
    "pre-order-products.store": [],
    "pre-order-products.show": [
        {
            "name": "pre_order_product",
            "required": true
        }
    ],
    "pre-order-products.edit": [
        {
            "name": "pre_order_product",
            "required": true
        }
    ],
    "pre-order-products.update": [
        {
            "name": "pre_order_product",
            "required": true
        }
    ],
    "pre-order-products.destroy": [
        {
            "name": "pre_order_product",
            "required": true
        }
    ],
    "order-types.index": [],
    "order-types.create": [],
    "order-types.store": [],
    "order-types.show": [
        {
            "name": "order_type",
            "required": true
        }
    ],
    "order-types.edit": [
        {
            "name": "order_type",
            "required": true
        }
    ],
    "order-types.update": [
        {
            "name": "order_type",
            "required": true
        }
    ],
    "order-types.destroy": [
        {
            "name": "order_type",
            "required": true
        }
    ],
    "collection-days.index": [],
    "collection-days.create": [],
    "collection-days.store": [],
    "collection-days.show": [
        {
            "name": "collection_day",
            "required": true
        }
    ],
    "collection-days.edit": [
        {
            "name": "collection_day",
            "required": true
        }
    ],
    "collection-days.update": [
        {
            "name": "collection_day",
            "required": true
        }
    ],
    "collection-days.destroy": [
        {
            "name": "collection_day",
            "required": true
        }
    ],
    "expense-budget.export": [],
    "expense-budget.index": [],
    "expense-budget.submission-tracker": [],
    "expense-budget.items.activity-logs": [
        {
            "name": "expenseBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "expense-budget.create": [],
    "expense-budget.store": [],
    "expense-budget.prev-budget": [],
    "expense-budget.budgeted-items": [],
    "expense-budget.items.update": [
        {
            "name": "expenseBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "expense-budget.items.destroy": [
        {
            "name": "expenseBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-budget.export": [],
    "sales-budget.index": [],
    "sales-budget.create": [],
    "sales-budget.store": [],
    "sales-budget.check": [],
    "sales-budget.period-data": [],
    "sales-budget.logs": [],
    "sales-budget.prev-expense": [],
    "sales-budget.edit": [
        {
            "name": "salesBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-budget.update": [
        {
            "name": "salesBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "sales-budget.destroy": [
        {
            "name": "salesBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "banks.index": [],
    "banks.store": [],
    "banks.update": [
        {
            "name": "bank",
            "required": true,
            "binding": "id"
        }
    ],
    "banks.destroy": [
        {
            "name": "bank",
            "required": true,
            "binding": "id"
        }
    ],
    "bank-branches.index": [],
    "bank-branches.store": [],
    "bank-branches.update": [
        {
            "name": "bank_branch",
            "required": true
        }
    ],
    "bank-branches.destroy": [
        {
            "name": "bank_branch",
            "required": true
        }
    ],
    "bank-balances.index": [],
    "bank-balances.store": [],
    "bank-balances.update": [
        {
            "name": "bank_balance",
            "required": true
        }
    ],
    "bank-balances.destroy": [
        {
            "name": "bank_balance",
            "required": true
        }
    ],
    "bank-balances.show": [
        {
            "name": "bank_balance",
            "required": true
        }
    ],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
